export const API_KEY = 'd61963ba96aea8547f4857bc75df7c51';

export const GET_LOCALITY = 'GET_PLACE';
export const GET_WEATHER_CONDITIONS = 'GET_WEATHER_CONDITIONS';
export const SET_FILTER = 'SET_FILTER';

export const SET_PARAM_DIAGRAM = 'SET_PARAM_DIAGRAM';
